name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Debug secrets
        run: |
          echo "HOST set: ${{ secrets.SSH_HOST != '' }}"
          echo "USER set: ${{ secrets.SSH_USER != '' }}"
          echo "KEY set: ${{ secrets.SSH_PRIVATE_KEY != '' }}"

      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            whoami
            hostname
            pwd
            ls -la /home/ubuntu/apps/kuspba
            bash /home/ubuntu/apps/kuspba/deploy.sh
